version: '3'

services:
  web:  # コンテナのサービス名をwebに設定
    container_name: php-book-app-web
    build:
      context: .
      dockerfile: ./Docker/php/Dockerfile
    # ディレクトリのマウントの設定
    volumes:
      - .:/var/www/html:cached
    # 環境変数の読み込み
    environment:
      - APP_DEFAULT_LOCALE=ja_JP
      - APP_DEFAULT_TIMEZONE=Asia/Tokyo
      - DATABASE_HOST=php-book-app-db
      - DATABASE_USER=root
      - DATABASE_PASS=secret
      - DATABASE_NAME=qa_app
    # docker-init-setup.shを実行し、その後apache2-foregroundを実行する
    # ここでは、公式イメージphp:7.2-apacheの CMD ["apache2-foreground"]を上書き？している
    command: bash -c "sh docker-init-setup.sh && apache2-foreground"
    # ホストの5000番ポートをゲストの80番ポートにポートフォワード
    ports:
      - "5000:80"

  db: # MySQL用のコンテナのサービス名
    container_name: php-book-app-db # コンテナ名
    build:
      context: .
      dockerfile: ./Docker/mysql/Dockerfile
    volumes:
      - ./Docker/mysql/sqls:/docker-entrypoint-initdb.d # sqlファイルをコンテナの/docker-entrypoint-initdb.dにマウント
      - ./Docker/mysql/data:/var/lib/mysql # データの永続化設定
    environment:
      - MYSQL_ROOT_PASSWORD=secret # rootユーザーのパスワード
    ports:
      - "13306:3306"

